# This is how often, in seconds, the server will contact your WordPress installation
# to see if there are donations that need made.
update_interval = 1500

# You must set this to your WordPress site URL.  If you installed WordPress in a
# subdirectory, it should point there.
url = "http://playground.dev"

# This must match the WordPress key in your admin panel for WooMinecraft
# This is a key that YOU set, both needing to be identical in the admin panel
# and in this config file
# For security purposes, you MUST NOT leave this empty.
key = ""

# Set to true in order to toggle debug information
debug = false
